"""
Turkish viral sentence pools for Reels.
Categories: emotional, sarcastic, deep, romantic.
8-12 words, no emojis, no end punctuation, no quotes.
Modern daily Turkish, young audience.
"""

EMOTIONAL = [
    "İnsan alışıyor ama eksilmiyor",
    "Bazı suskunluklar çok şey anlatır",
    "Kalbin yorulduğu yerde mantık konuşur",
    "Her gülüş mutlu olduğun anlamına gelmez",
    "Bazen en çok yanında olanlar en uzak hissettirir",
    "Yorgun bir kalple gülmek zor iş",
    "İçinde bir şeyler kırıldığında ses çıkmaz",
    "Bırakmak değil bırakılmak yoruyor insanı",
    "Bazı acılar kelimelerle anlatılmaz",
    "Geceler uzadıkça düşünceler derinleşir",
    "Kimse senin yükünü taşımaz taşıyamaz",
    "Bazen en sessiz insanlar en çok acı çeker",
    "Yalnızlık bazen kalabalıktan daha iyi",
    "Her şey geçer ama izi kalır",
    "Bazı insanlar gider ama boşlukları dolar mı",
    "Gülümsemek en kolay yalan",
    "İçindeki fırtınayı kimse görmüyor",
    "Bazen en güçlü görünenler en çok kırılgandır",
    "Gece olunca her şey daha ağır gelir",
    "Kaybetmek değil kaybetmeye alışmak zor",
    "Bazı yaralar görünmez ama hep kanar",
    "Kimse senin hikayeni tam bilmez",
    "Yorgunluk bazen bedenden değil yürekten gelir",
    "Bazen susmak en iyi cevaptır",
    "Herkes gider bir sen kalırsın kendinle",
    "Bazı anlar tekrar etmez o yüzden ağır",
    "İnsan bazen kendine bile yabancı hisseder",
    "En çok güvendiğin insanlar en çok incitir",
    "Bazen hiçbir şey yapmak en zor olandır",
    "Gece düşüncelerin en çok seni bulduğu zaman",
    "Bırakıp gitmek kolay kalan zor",
    "Her şey biter ama bazı şeyler bitmez",
    "İçindeki boşluk bazen hiç dolmaz",
    "Bazı insanlar gider geriye sadece sessizlik kalır",
    "En sessiz çığlıklar en derin olanlardır",
    "Yalnız olmak ile yalnız hissetmek farklı",
    "Bazen en iyi terapi ağlamaktır",
    "Herkes bir gün gider sadece anılar kalır",
]

SARCASTIC = [
    "Teşekkürler hayat yine güzel bir gün verdin",
    "Her şey yolunda deyip duruyorlar nerede yol",
    "Olur öyle denince içim rahatlamıyor nedense",
    "Sabır dediler sabrettim hala bekliyorum",
    "Pozitif ol diyorlar ama hayat negatif veriyor",
    "Her şeyin bir sebebi varmış peki bu ne",
    "Zaman her şeyi iyileştirir diyorlar hala bekliyorum",
    "Güçlü ol diyorlar yorgunum artık",
    "Her şey güzel olacakmış nerede o güzel",
    "İyi düşün iyi olsun diyorlar düşündüm olmadı",
    "Elbet bir gün diyorlar hangi gün",
    "Her şey yoluna girer diyorlar yol nerede",
    "Olur öyle geçer diyorlar geçmedi",
    "Sabret diyorlar sabrettim yine de olmadı",
    "Pozitif enerji diyorlar enerjim tükendi",
    "Her şeyin bir anlamı varmış bu ne anlama geliyor",
    "Zaman her şeyi halleder diyorlar zaman geçti hallolmadı",
    "Güçlü kal diyorlar gücüm kalmadı",
    "Mutlu ol diyorlar mutluluk nerede satılıyor",
    "Her şey düzelecekmiş ne zaman düzelecek",
    "İyi düşün diyorlar düşündüm kötü oldu",
    "Elbet geçer diyorlar geçmedi hala buradayım",
    "Her şey yolunda diyorlar yol nerede gösterin",
    "Olur öyle diyorlar olmuyor işte",
    "Sabır en büyük erdemmiş sabrım bitti",
    "Pozitif olun diyorlar negatif hayat veriyor",
    "Her şeyin bir hikmeti varmış bu ne hikmet",
    "Zaman ilacıymış zaman geçti iyileşmedim",
    "Güçlü olun diyorlar gücüm kalmadı artık",
    "Mutluluk içinde diyorlar içimde bulamıyorum",
    "Her şey düzelir diyorlar düzelmedi",
]

DEEP = [
    "Hayat bazen seni sınamak için durdurur",
    "Gerçek yolculuk içe doğru olandır",
    "Bazen kaybetmek kazanmaktan daha çok öğretir",
    "Sessizlik bazen en derin cevaptır",
    "İnsan kendini kaybettiğinde bulur bazen",
    "En karanlık gece en parlak yıldızı gösterir",
    "Bırakmak bazen tutmaktan daha güçlü olmaktır",
    "Gerçek cesaret korkuya rağmen yürümektir",
    "Her son bir başlangıç saklar içinde",
    "En derin acılar en büyük dönüşümleri getirir",
    "Yol bazen kaybolduğunda bulunur",
    "Sessiz kalan bazen en çok şey bilir",
    "İnsan ancak kırıldığında gerçeği görür",
    "En uzak mesafe iki insan arasındaki sessizliktir",
    "Bırakmak bazen en büyük tutuştur",
    "Gerçek zenginlik içinde taşıdığın huzurdur",
    "Her düşüş bir yükselişin başlangıcıdır",
    "En karanlık an en aydınlığa en yakın olandır",
    "Yolculuk bazen varıştan daha değerlidir",
    "Sessizlik bazen en güçlü dil olur",
    "İnsan ancak kaybettiğinde anlar değerini",
    "En derin deniz en sessiz olandır",
    "Bırakmak bazen en büyük tutuştur",
    "Gerçek özgürlük hiçbir şeye bağlı olmamaktır",
    "Her gece bir sabah saklar",
    "En büyük ders sessizlikten gelir",
    "Yol bazen en karanlıkta aydınlanır",
    "Sessiz kalan bazen en çok konuşandır",
    "İnsan kendini ancak yalnızken tanır",
    "En uzun yol içe giden yoldur",
]

ROMANTIC = [
    "Bazen bir bakış her şeyi anlatır",
    "Seninle olmak yalnız olmamak gibi",
    "Bazı insanlar kalbe yazılır silinmez",
    "Sevmek bazen sessizce beklemektir",
    "Seninle geçen her an ayrı kıymetli",
    "Bazen kalp kafadan önce bilir",
    "Bir insan bir hayat değiştirebilir",
    "Seninle olunca zaman durur",
    "Bazı bakışlar kelimelerden güçlüdür",
    "Sevmek bazen hiçbir karşılık beklememektir",
    "Seninle her şey daha anlamlı",
    "Bazen bir ses her şeyi değiştirir",
    "Kalp bazen aklı dinlemez",
    "Seninle yürümek ayrı güzel",
    "Bazı insanlar ruhuna dokunur",
    "Sevmek bazen sadece orada olmaktır",
    "Seninle olmak ev hissi",
    "Bazen bir kişi tüm dünyaya bedel",
    "Kalp seçer bazen kafa karışır",
    "Seninle gece bile gündüz gibi",
    "Bazı anlar tekrar yaşanmak ister",
    "Sevmek bazen sessizce izlemektir",
    "Seninle her yol kısa gelir",
    "Bazen bir dokunuş her şeyi anlatır",
    "Kalp bazen geç kalır bazen erken",
    "Seninle susmak bile güzel",
    "Bazı insanlar bir kez gelir",
    "Sevmek bazen beklemektir",
    "Seninle olunca her şey yerli yerinde",
    "Bazen bir isim tüm cümleleri doldurur",
]

# Export by category for weighted random choice
POOLS = {
    "emotional": EMOTIONAL,
    "sarcastic": SARCASTIC,
    "deep": DEEP,
    "romantic": ROMANTIC,
}
